baseURL: https://ti-yao.github.io/homepage/
title: Translational Cardiac MRI Group
menu:
  main:
  - identifier: research
    name: Research
    url: /research/
    weight: 10
  - identifier: publications
    name: Publications
    url: /publications/
    weight: 20
  - identifier: people
    name: People
    url: /people/
    weight: 30
  - identifier: news
    name: News
    url: /news/
    weight: 40
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 100
params:
  description: Developing and validating novel methods of imaging the cardiovascular
    system
  img_home: img/home/banner.jpg
  img_404: img/404.jpg
  sponsors:
  - img/sponsors/ucl.png
  - img/sponsors/bhf.png
  - img/sponsors/gosh.png
  - img/sponsors/royalfree.png
  email: rmhitly@ucl.ac.uk
  social:
    github: mrphys
  highlighted_pubs:
    1:
      title: 'Defining diastolic dysfunction post-Fontan: Threshold, risk factors,
        and associations with outcomes.'
      year: 2025
      journal: American heart journal
      link: https://doi.org/10.1016/j.ahj.2025.07.007
    2:
      title: Fully automated measurement of aortic pulse wave velocity from routine
        cardiac MRI studies.
      year: 2025
      journal: Magnetic resonance imaging
      link: https://doi.org/10.1016/j.mri.2025.110442
    3:
      title: Increased Body Mass Index and Ventricular Cardiac Magnetic Resonance
        Characteristics in Adults With Fontan Circulation.
      year: 2025
      journal: JACC. Advances
      link: https://doi.org/10.1016/j.jacadv.2025.102094
    4:
      title: A lumped parameter model of the coronary circulation incorporating time-varying
        resistance, intramyocardial pressure and vascular compliance.
      year: 2025
      journal: Journal of biomechanics
      link: https://doi.org/10.1016/j.jbiomech.2025.112679
    5:
      title: 'Transthyretin amyloid cardiomyopathy: natural history and treatment
        response assessed by cardiovascular magnetic resonance.'
      year: 2025
      journal: European heart journal
      link: https://doi.org/10.1093/eurheartj/ehaf412
    6:
      title: Cardiopulmonary Exercise Testing With Exercise Echocardiography to Assess
        Treatment Response in Transthyretin Amyloid Cardiomyopathy.
      year: 2025
      journal: JACC. Heart failure
      link: https://doi.org/10.1016/j.jchf.2025.01.020
    7:
      title: 'Predicting Peri-Operative Cardiorespiratory Adverse Events in Children
        with Idiopathic Pulmonary Arterial Hypertension Undergoing Cardiac Catheterization
        Using Echocardiography: A Cohort Study.'
      year: 2025
      journal: Pediatric cardiology
      link: https://doi.org/10.1007/s00246-024-03447-3
    8:
      title: A machine learning algorithm for creating isotropic 3D aortic segmentations
        from routine cardiac MR localizers.
      year: 2025
      journal: Magnetic resonance imaging
      link: https://doi.org/10.1016/j.mri.2024.110253
    9:
      title: Cardiac MRI Predictors of Arrhythmic Sudden Cardiac Events in Patients
        With Fontan Circulation.
      year: 2024
      journal: Journal of the American College of Cardiology
      link: https://doi.org/10.1016/j.jacc.2024.08.063
    10:
      title: 'Clinical impact of novel cardiovascular magnetic resonance technology
        on patients with congenital heart disease: a scientific statement of the Association
        for European Pediatric and Congenital Cardiology and the European Association
        of Cardiovascular Imaging of the European Society of Cardiology.'
      year: 2024
      journal: European heart journal. Cardiovascular Imaging
      link: https://doi.org/10.1093/ehjci/jeae172
